using System.Globalization;
using System.Windows;
using DiskScope.Core.Models;
using DiskScope.Models;

namespace DiskScope.Services;

public static class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["NavOverview"] = "⌂   Overview",
        ["NavOverviewName"] = "Overview",
        ["NavResults"] = "☷   Scan results",
        ["NavResultsName"] = "Scan results",
        ["NavSettings"] = "⚙   Settings",
        ["NavSettingsName"] = "Settings",
        ["NavAbout"] = "ⓘ   About",
        ["NavAboutName"] = "About DiskScope",
        ["CreatedBy"] = "Created by pcalsys",
        ["VersionFormat"] = "Version {0}",
        ["Language"] = "Language",
        ["OverviewTitle"] = "Understand your storage",
        ["OverviewSubtitle"] = "See what is using your storage. Know what not to delete.",
        ["ScanFolderTitle"] = "Scan a folder",
        ["ScanFolderDescription"] = "Choose any local, external, or network folder. DiskScope only reads file metadata.",
        ["ChooseFolder"] = "Choose folder…",
        ["ChooseFolderName"] = "Choose a folder to scan",
        ["AvailableDrives"] = "Available drives",
        ["Refresh"] = "Refresh",
        ["ScanDrive"] = "Scan drive",
        ["SafetyDisclaimer"] = "DiskScope provides cautious guidance, never a guarantee that a file is safe to delete.",
        ["CancelScan"] = "Cancel scan",
        ["Files"] = "Files",
        ["TotalSize"] = "Total size",
        ["FoldersVisited"] = "Folders visited",
        ["SkippedUnavailable"] = "Skipped / unavailable",
        ["SearchToolTip"] = "Search names, paths, extensions, and file types",
        ["SearchResultsName"] = "Search scan results",
        ["MinimumSizeName"] = "Minimum file size",
        ["CategoryName"] = "File category",
        ["LargestFolders"] = "Largest folders",
        ["Name"] = "Name",
        ["Size"] = "Size",
        ["Location"] = "Location",
        ["Type"] = "Type",
        ["Modified"] = "Modified",
        ["Safety"] = "Safety",
        ["Folder"] = "Folder",
        ["ScannedFilesName"] = "Scanned files sorted by size",
        ["LargestFoldersName"] = "Largest folders",
        ["SelectFilePrompt"] = "Select a file to see why DiskScope classified it and which actions are appropriate.",
        ["SafetyAssessment"] = "Safety assessment",
        ["WhatThisMeans"] = "What this means",
        ["Recommendation"] = "Recommendation",
        ["Open"] = "Open",
        ["ShowInExplorer"] = "Show in Explorer",
        ["CopyPath"] = "Copy path",
        ["Properties"] = "Properties",
        ["MoveToRecycleBin"] = "Move to Recycle Bin",
        ["ProtectedFile"] = "Protected by DiskScope: this Windows file cannot be moved to the Recycle Bin here.",
        ["SettingsTitle"] = "Settings",
        ["SettingsSubtitle"] = "Control appearance and what future scans include.",
        ["Appearance"] = "Appearance",
        ["Theme"] = "Theme",
        ["WindowsThemeHint"] = "Windows (automatic) follows the Windows app theme and updates while DiskScope is open.",
        ["FileSizeDisplay"] = "File size display",
        ["ScanningSettings"] = "Scanning",
        ["IncludeHidden"] = "Include hidden files",
        ["HiddenHint"] = "Hidden files are omitted by default to reduce clutter.",
        ["IncludeSystem"] = "Include Windows system files",
        ["SystemHint"] = "System files receive extra protection. Filesystem links and mount points are never followed.",
        ["FileActions"] = "File actions",
        ["ConfirmRecycle"] = "Confirm before moving files to the Recycle Bin",
        ["HighRiskHint"] = "High-risk files always require confirmation, regardless of this setting.",
        ["PrivacyPromise"] = "Privacy promise",
        ["PrivacyText"] = "DiskScope has no account, cloud service, telemetry, analytics, ads, or network requirement. File names and paths are processed only in memory on this computer.",
        ["AboutTitle"] = "About DiskScope",
        ["AboutDescription"] = "DiskScope is a local Windows storage analyzer that pairs size insights with cautious, understandable file-safety guidance.",
        ["License"] = "License",
        ["SourceCode"] = "Source code",
        ["OpenGitHub"] = "Open GitHub project",
        ["Privacy"] = "Privacy",
        ["NoDataLeaves"] = "No data leaves this device.",
        ["AboutSafety"] = "Safety guidance is based on file locations and types. It is intentionally conservative and cannot replace backups, vendor documentation, or professional system administration.",
        ["ThemeSystem"] = "Windows (automatic)",
        ["ThemeLight"] = "Light",
        ["ThemeDark"] = "Dark",
        ["SizeAutomatic"] = "Automatic",
        ["SizeBinary"] = "Binary (KiB, MiB, GiB)",
        ["SizeDecimal"] = "Decimal (KB, MB, GB)",
        ["FilterAnySize"] = "Any size",
        ["FilterOver100Mb"] = "Over 100 MB",
        ["FilterOver500Mb"] = "Over 500 MB",
        ["FilterOver1Gb"] = "Over 1 GB",
        ["FilterOver5Gb"] = "Over 5 GB",
        ["CategoryAll"] = "All types",
        ["CategoryVideos"] = "Videos",
        ["CategoryImages"] = "Images",
        ["CategoryArchives"] = "Archives",
        ["CategoryPrograms"] = "Programs",
        ["CategoryDocuments"] = "Documents",
        ["CategoryAudio"] = "Audio",
        ["CategoryOther"] = "Other",
        ["ReadyHeading"] = "Ready to scan",
        ["ReadyDetail"] = "Choose a drive or folder to understand what is using your storage.",
        ["ScanningHeading"] = "Scanning storage…",
        ["ScanningInitial"] = "Reading file metadata locally. No file information leaves this computer.",
        ["ScanningPath"] = "Scanning {0}",
        ["CancelledHeading"] = "Scan cancelled",
        ["CancelledDetail"] = "Partial results are available. {0} files were found before cancellation.",
        ["CompleteHeading"] = "Scan complete",
        ["CompleteDetail"] = "Found {0} files using {1} in {2}.",
        ["FailedHeading"] = "Scan could not be completed",
        ["FailedDetail"] = "DiskScope could not read this location. Check that it exists and that you have access.",
        ["ShownCount"] = "{0} shown",
        ["DriveNotReady"] = "Drive is not ready",
        ["DriveUsage"] = "{0} of {1} used",
        ["DriveFixed"] = "Fixed",
        ["DriveRemovable"] = "Removable",
        ["DriveNetwork"] = "Network",
        ["DriveCdRom"] = "Optical",
        ["DriveRam"] = "RAM disk",
        ["DriveUnknown"] = "Unknown",
        ["GenericFile"] = "File",
        ["FileTypeFormat"] = "{0} file",
        ["CriticalTitle"] = "Critical system file",
        ["CriticalExplanation"] = "This file appears to be part of Windows startup, the registry, or another critical operating-system component.",
        ["CriticalRecommendation"] = "Do not move or delete this file. Use Windows recovery or servicing tools if it is damaged.",
        ["WindowsTitle"] = "Windows system file",
        ["WindowsExplanation"] = "This file is stored in a protected Windows location and may be required by the operating system or a Windows feature.",
        ["WindowsRecommendation"] = "Do not delete it manually. Use Windows Settings, Disk Cleanup, or DISM for supported maintenance.",
        ["ProgramTitle"] = "Program file",
        ["ProgramExplanation"] = "This file is executable or probably belongs to an installed application.",
        ["ProgramRecommendation"] = "Use the program's uninstaller or Windows Settings instead of deleting individual files.",
        ["TemporaryTitle"] = "Temporary file",
        ["TemporaryExplanation"] = "This file is in a location commonly used for temporary data, but an application may still be using it.",
        ["TemporaryRecommendation"] = "Close related applications first. Prefer Windows Storage cleanup and review the file before removal.",
        ["ApplicationDataTitle"] = "Application data",
        ["ApplicationDataExplanation"] = "This file likely stores application settings, caches, databases, or user state.",
        ["ApplicationDataRecommendation"] = "Remove it only when you understand which application created it. Uninstalling or resetting the app is usually safer.",
        ["PersonalTitle"] = "Personal file",
        ["PersonalExplanation"] = "This file is in a user-content location and was likely created, downloaded, or saved by a person.",
        ["PersonalRecommendation"] = "Open or back up the file before removing it. DiskScope cannot guarantee that any file is safe to delete.",
        ["UnknownTitle"] = "Unknown file",
        ["UnknownExplanation"] = "DiskScope cannot reliably determine who created this file or whether another program depends on it.",
        ["UnknownRecommendation"] = "Inspect the file and its containing folder before taking action. Keep a backup if you are uncertain.",
        ["ChooseFolderDialog"] = "Choose a folder to analyze",
        ["FolderUnavailable"] = "The folder no longer exists or is unavailable.",
        ["ScanInProgressTitle"] = "Scan in progress",
        ["ScanInProgressMessage"] = "Wait for the scan to finish or cancel it before moving a result to the Recycle Bin.",
        ["ProtectedSystemTitle"] = "Protected system file",
        ["ProtectedSystemMessage"] = "DiskScope blocks this action because the file appears to be part of Windows. Use supported Windows maintenance or recovery tools instead.",
        ["HighRiskWarning"] = "This file may be used by an application or its purpose is uncertain. Removing it could cause data loss or break software.\n\n",
        ["RecycleQuestion"] = "Move this file to the Recycle Bin?\n\n{0}\n{1}\n\nDiskScope cannot guarantee that any file is safe to remove.",
        ["ConfirmFileAction"] = "Confirm file action",
        ["ActionErrorTitle"] = "DiskScope could not complete the action",
        ["UnexpectedError"] = "DiskScope encountered an unexpected problem and could not complete the action.\n\n{0}",
        ["PropertiesError"] = "Windows could not open the file properties dialog.",
        ["FileUnavailable"] = "The file no longer exists or is unavailable.",
        ["RecycleUnavailable"] = "Windows does not provide a recoverable local Recycle Bin for this location. DiskScope will not delete the file permanently.",
        ["ReparseRecycleBlocked"] = "DiskScope will not move a file reached through a filesystem link or mount point to the Recycle Bin."
    };

    private static readonly IReadOnlyDictionary<string, string> German = new Dictionary<string, string>
    {
        ["NavOverview"] = "⌂   Übersicht",
        ["NavOverviewName"] = "Übersicht",
        ["NavResults"] = "☷   Scanergebnisse",
        ["NavResultsName"] = "Scanergebnisse",
        ["NavSettings"] = "⚙   Einstellungen",
        ["NavSettingsName"] = "Einstellungen",
        ["NavAbout"] = "ⓘ   Über DiskScope",
        ["NavAboutName"] = "Über DiskScope",
        ["CreatedBy"] = "Erstellt von pcalsys",
        ["VersionFormat"] = "Version {0}",
        ["Language"] = "Sprache",
        ["OverviewTitle"] = "Verstehe deinen Speicher",
        ["OverviewSubtitle"] = "Sieh, was Speicher belegt – und was du besser nicht löschst.",
        ["ScanFolderTitle"] = "Ordner scannen",
        ["ScanFolderDescription"] = "Wähle einen lokalen, externen oder Netzwerkordner. DiskScope liest nur Dateimetadaten.",
        ["ChooseFolder"] = "Ordner wählen…",
        ["ChooseFolderName"] = "Ordner zum Scannen auswählen",
        ["AvailableDrives"] = "Verfügbare Laufwerke",
        ["Refresh"] = "Aktualisieren",
        ["ScanDrive"] = "Laufwerk scannen",
        ["SafetyDisclaimer"] = "DiskScope gibt vorsichtige Hinweise, aber niemals eine Garantie, dass eine Datei sicher gelöscht werden kann.",
        ["CancelScan"] = "Scan abbrechen",
        ["Files"] = "Dateien",
        ["TotalSize"] = "Gesamtgröße",
        ["FoldersVisited"] = "Besuchte Ordner",
        ["SkippedUnavailable"] = "Übersprungen / nicht verfügbar",
        ["SearchToolTip"] = "Namen, Pfade, Erweiterungen und Dateitypen durchsuchen",
        ["SearchResultsName"] = "Scanergebnisse durchsuchen",
        ["MinimumSizeName"] = "Mindestdateigröße",
        ["CategoryName"] = "Dateikategorie",
        ["LargestFolders"] = "Größte Ordner",
        ["Name"] = "Name",
        ["Size"] = "Größe",
        ["Location"] = "Speicherort",
        ["Type"] = "Typ",
        ["Modified"] = "Geändert",
        ["Safety"] = "Sicherheit",
        ["Folder"] = "Ordner",
        ["ScannedFilesName"] = "Gescannte Dateien nach Größe sortiert",
        ["LargestFoldersName"] = "Größte Ordner",
        ["SelectFilePrompt"] = "Wähle eine Datei aus, um die Einstufung und passende Aktionen zu sehen.",
        ["SafetyAssessment"] = "Sicherheitsbewertung",
        ["WhatThisMeans"] = "Was das bedeutet",
        ["Recommendation"] = "Empfehlung",
        ["Open"] = "Öffnen",
        ["ShowInExplorer"] = "Im Explorer anzeigen",
        ["CopyPath"] = "Pfad kopieren",
        ["Properties"] = "Eigenschaften",
        ["MoveToRecycleBin"] = "In den Papierkorb verschieben",
        ["ProtectedFile"] = "Von DiskScope geschützt: Diese Windows-Datei kann hier nicht in den Papierkorb verschoben werden.",
        ["SettingsTitle"] = "Einstellungen",
        ["SettingsSubtitle"] = "Darstellung und Inhalt künftiger Scans festlegen.",
        ["Appearance"] = "Darstellung",
        ["Theme"] = "Design",
        ["WindowsThemeHint"] = "Windows (automatisch) folgt dem Windows-App-Design und aktualisiert DiskScope im laufenden Betrieb.",
        ["FileSizeDisplay"] = "Anzeige der Dateigröße",
        ["ScanningSettings"] = "Scannen",
        ["IncludeHidden"] = "Versteckte Dateien einbeziehen",
        ["HiddenHint"] = "Versteckte Dateien werden standardmäßig ausgeblendet.",
        ["IncludeSystem"] = "Windows-Systemdateien einbeziehen",
        ["SystemHint"] = "Systemdateien erhalten zusätzlichen Schutz. Dateisystemlinks und Einhängepunkte werden nie verfolgt.",
        ["FileActions"] = "Dateiaktionen",
        ["ConfirmRecycle"] = "Vor dem Verschieben in den Papierkorb bestätigen",
        ["HighRiskHint"] = "Bei riskanten Dateien ist die Bestätigung immer erforderlich.",
        ["PrivacyPromise"] = "Datenschutzversprechen",
        ["PrivacyText"] = "DiskScope benötigt weder Konto noch Cloud, Telemetrie, Analysen, Werbung oder Netzwerk. Dateinamen und Pfade werden nur im Arbeitsspeicher dieses Computers verarbeitet.",
        ["AboutTitle"] = "Über DiskScope",
        ["AboutDescription"] = "DiskScope ist eine lokale Windows-Speicheranalyse mit verständlichen, vorsichtigen Hinweisen zur Dateisicherheit.",
        ["License"] = "Lizenz",
        ["SourceCode"] = "Quellcode",
        ["OpenGitHub"] = "GitHub-Projekt öffnen",
        ["Privacy"] = "Datenschutz",
        ["NoDataLeaves"] = "Keine Daten verlassen dieses Gerät.",
        ["AboutSafety"] = "Die Sicherheitshinweise basieren auf Speicherorten und Dateitypen. Sie sind bewusst vorsichtig und ersetzen weder Backups noch Herstellerdokumentation oder professionelle Systemverwaltung.",
        ["ThemeSystem"] = "Windows (automatisch)",
        ["ThemeLight"] = "Hell",
        ["ThemeDark"] = "Dunkel",
        ["SizeAutomatic"] = "Automatisch",
        ["SizeBinary"] = "Binär (KiB, MiB, GiB)",
        ["SizeDecimal"] = "Dezimal (KB, MB, GB)",
        ["FilterAnySize"] = "Beliebige Größe",
        ["FilterOver100Mb"] = "Über 100 MB",
        ["FilterOver500Mb"] = "Über 500 MB",
        ["FilterOver1Gb"] = "Über 1 GB",
        ["FilterOver5Gb"] = "Über 5 GB",
        ["CategoryAll"] = "Alle Typen",
        ["CategoryVideos"] = "Videos",
        ["CategoryImages"] = "Bilder",
        ["CategoryArchives"] = "Archive",
        ["CategoryPrograms"] = "Programme",
        ["CategoryDocuments"] = "Dokumente",
        ["CategoryAudio"] = "Audio",
        ["CategoryOther"] = "Sonstige",
        ["ReadyHeading"] = "Bereit zum Scannen",
        ["ReadyDetail"] = "Wähle ein Laufwerk oder einen Ordner aus, um die Speicherbelegung zu verstehen.",
        ["ScanningHeading"] = "Speicher wird gescannt…",
        ["ScanningInitial"] = "Dateimetadaten werden lokal gelesen. Keine Dateiinformationen verlassen diesen Computer.",
        ["ScanningPath"] = "Scanne {0}",
        ["CancelledHeading"] = "Scan abgebrochen",
        ["CancelledDetail"] = "Teilergebnisse sind verfügbar. Vor dem Abbruch wurden {0} Dateien gefunden.",
        ["CompleteHeading"] = "Scan abgeschlossen",
        ["CompleteDetail"] = "{0} Dateien mit insgesamt {1} wurden in {2} gefunden.",
        ["FailedHeading"] = "Scan konnte nicht abgeschlossen werden",
        ["FailedDetail"] = "DiskScope konnte diesen Speicherort nicht lesen. Prüfe, ob er existiert und du darauf zugreifen darfst.",
        ["ShownCount"] = "{0} angezeigt",
        ["DriveNotReady"] = "Laufwerk ist nicht bereit",
        ["DriveUsage"] = "{0} von {1} belegt",
        ["DriveFixed"] = "Lokal",
        ["DriveRemovable"] = "Wechseldatenträger",
        ["DriveNetwork"] = "Netzwerk",
        ["DriveCdRom"] = "Optisch",
        ["DriveRam"] = "RAM-Laufwerk",
        ["DriveUnknown"] = "Unbekannt",
        ["GenericFile"] = "Datei",
        ["FileTypeFormat"] = "{0}-Datei",
        ["CriticalTitle"] = "Kritische Systemdatei",
        ["CriticalExplanation"] = "Diese Datei scheint zum Windows-Start, zur Registrierung oder zu einer anderen kritischen Betriebssystemkomponente zu gehören.",
        ["CriticalRecommendation"] = "Verschiebe oder lösche diese Datei nicht. Nutze bei Schäden die Windows-Wiederherstellung oder Wartungswerkzeuge.",
        ["WindowsTitle"] = "Windows-Systemdatei",
        ["WindowsExplanation"] = "Diese Datei liegt in einem geschützten Windows-Bereich und kann für das Betriebssystem oder eine Windows-Funktion erforderlich sein.",
        ["WindowsRecommendation"] = "Lösche sie nicht manuell. Nutze Windows-Einstellungen, Datenträgerbereinigung oder DISM.",
        ["ProgramTitle"] = "Programmdatei",
        ["ProgramExplanation"] = "Diese Datei ist ausführbar oder gehört wahrscheinlich zu einer installierten Anwendung.",
        ["ProgramRecommendation"] = "Nutze das Deinstallationsprogramm oder die Windows-Einstellungen, statt einzelne Dateien zu löschen.",
        ["TemporaryTitle"] = "Temporäre Datei",
        ["TemporaryExplanation"] = "Diese Datei liegt in einem üblichen Bereich für temporäre Daten, könnte aber noch von einer Anwendung verwendet werden.",
        ["TemporaryRecommendation"] = "Schließe zuerst zugehörige Anwendungen. Nutze bevorzugt die Windows-Speicherbereinigung und prüfe die Datei vor dem Entfernen.",
        ["ApplicationDataTitle"] = "Anwendungsdaten",
        ["ApplicationDataExplanation"] = "Diese Datei enthält wahrscheinlich Anwendungseinstellungen, Caches, Datenbanken oder Benutzerstatus.",
        ["ApplicationDataRecommendation"] = "Entferne sie nur, wenn du die erstellende Anwendung kennst. Eine Deinstallation oder Zurücksetzung ist meist sicherer.",
        ["PersonalTitle"] = "Persönliche Datei",
        ["PersonalExplanation"] = "Diese Datei liegt in einem Benutzerordner und wurde wahrscheinlich von einer Person erstellt, heruntergeladen oder gespeichert.",
        ["PersonalRecommendation"] = "Öffne oder sichere die Datei vor dem Entfernen. DiskScope kann nicht garantieren, dass eine Datei sicher gelöscht werden kann.",
        ["UnknownTitle"] = "Unbekannte Datei",
        ["UnknownExplanation"] = "DiskScope kann nicht zuverlässig erkennen, wer diese Datei erstellt hat oder ob ein anderes Programm davon abhängt.",
        ["UnknownRecommendation"] = "Prüfe die Datei und den übergeordneten Ordner. Bewahre bei Unsicherheit eine Sicherung auf.",
        ["ChooseFolderDialog"] = "Ordner zur Analyse auswählen",
        ["FolderUnavailable"] = "Der Ordner existiert nicht mehr oder ist nicht verfügbar.",
        ["ScanInProgressTitle"] = "Scan läuft",
        ["ScanInProgressMessage"] = "Warte bis der Scan beendet ist oder brich ihn ab, bevor du ein Ergebnis in den Papierkorb verschiebst.",
        ["ProtectedSystemTitle"] = "Geschützte Systemdatei",
        ["ProtectedSystemMessage"] = "DiskScope blockiert diese Aktion, weil die Datei offenbar zu Windows gehört. Nutze stattdessen unterstützte Windows-Wartungs- oder Wiederherstellungswerkzeuge.",
        ["HighRiskWarning"] = "Diese Datei könnte von einer Anwendung verwendet werden oder ihr Zweck ist unklar. Das Entfernen kann Datenverlust verursachen oder Software beschädigen.\n\n",
        ["RecycleQuestion"] = "Diese Datei in den Papierkorb verschieben?\n\n{0}\n{1}\n\nDiskScope kann nicht garantieren, dass eine Datei sicher entfernt werden kann.",
        ["ConfirmFileAction"] = "Dateiaktion bestätigen",
        ["ActionErrorTitle"] = "DiskScope konnte die Aktion nicht abschließen",
        ["UnexpectedError"] = "In DiskScope ist ein unerwartetes Problem aufgetreten. Die Aktion konnte nicht abgeschlossen werden.\n\n{0}",
        ["PropertiesError"] = "Windows konnte den Eigenschaften-Dialog nicht öffnen.",
        ["FileUnavailable"] = "Die Datei existiert nicht mehr oder ist nicht verfügbar.",
        ["RecycleUnavailable"] = "Windows bietet für diesen Speicherort keinen wiederherstellbaren lokalen Papierkorb. DiskScope löscht die Datei daher nicht dauerhaft.",
        ["ReparseRecycleBlocked"] = "DiskScope verschiebt keine Datei in den Papierkorb, die über einen Dateisystemlink oder Einhängepunkt erreicht wurde."
    };

    public static AppLanguage CurrentLanguage { get; private set; } = AppLanguage.English;

    static LocalizationService()
    {
        var missingGerman = English.Keys.Except(German.Keys, StringComparer.Ordinal).ToArray();
        var missingEnglish = German.Keys.Except(English.Keys, StringComparer.Ordinal).ToArray();
        if (missingGerman.Length == 0 && missingEnglish.Length == 0) return;

        throw new InvalidOperationException(
            $"Translation keys do not match. Missing German: {string.Join(", ", missingGerman)}; " +
            $"missing English: {string.Join(", ", missingEnglish)}.");
    }

    public static void Apply(AppLanguage language)
    {
        CurrentLanguage = language;
        var culture = CultureInfo.GetCultureInfo(language == AppLanguage.German ? "de-DE" : "en-US");
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
        CultureInfo.DefaultThreadCurrentCulture = culture;
        CultureInfo.DefaultThreadCurrentUICulture = culture;

        if (Application.Current is { } application)
        {
            foreach (var pair in GetStrings()) application.Resources[pair.Key] = pair.Value;
        }
    }

    public static string Get(string key) => GetStrings().TryGetValue(key, out var value) ? value : key;

    public static string Format(string key, params object[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), arguments);

    public static string GetFileTypeName(string extension) => string.IsNullOrWhiteSpace(extension)
        ? Get("GenericFile")
        : Format("FileTypeFormat", extension.TrimStart('.').ToUpperInvariant());

    public static string GetSafetyText(SafetyAssessment assessment, string part)
    {
        var prefix = assessment.Category switch
        {
            SafetyCategory.CriticalSystem => "Critical",
            SafetyCategory.WindowsSystem => "Windows",
            SafetyCategory.ProgramFile => "Program",
            SafetyCategory.Temporary => "Temporary",
            SafetyCategory.ApplicationData => "ApplicationData",
            SafetyCategory.Personal => "Personal",
            _ => "Unknown"
        };
        return Get(prefix + part);
    }

    private static IReadOnlyDictionary<string, string> GetStrings() =>
        CurrentLanguage == AppLanguage.German ? German : English;
}
